### ISSUE TITLE
BulletBot version number doesn't get update when updating BulletBot itself

### ISSUE THREAD

**Issue by StrangeRanger** [CodeBullet-Community/BulletBot#36]
# Problem
If BulletBot is updated and the version number is different, the installer will not change the version number located in `bot-config.json` to the new version number, automatically.

# Solution
Make the installer grab the current version of the bot, located in the `package.json`, and update the version number located in `bot-config.json`.

**Comment by Jet132** [comment]
A better solution would be removing the version number in `bot-config.json` altogether. It's useless if you can just get the version from the `package.json` file.

**Comment by StrangeRanger** [comment]
@Jet132 Then what would be in charge of grabbing the version number when using a command such as `serverinfo`, which displays the current bot version?

**Comment by Jet132** [comment]
it just grabs the version of `package.json`. There is even a native variable for that: `process.env.npm_package_version` (refer to <https://docs.npmjs.com/misc/scripts#packagejson-vars>)

**Comment by StrangeRanger** [comment]
The command itself grabs the version number?

**Comment by Jet132** [comment]
Yeah, but with the solution I proposed, the version number would be a global variable.

**Comment by StrangeRanger** [comment]
Alright sounds good

**Comment by StrangeRanger** [comment]
When the changes and the code that does this is added, we’ll have to remove 1 or 2 lines in `bot-config-setup.sh`. When the time comes, I can take care of that.

**Comment by Jet132** [comment]
was implemented in https://github.com/CodeBullet-Community/BulletBot/pull/39
