### ISSUE TITLE
Add a command that lists all the memebers of a specific role

### ISSUE THREAD

**Issue by StrangeRanger** [CodeBullet-Community/BulletBot#72]
**Describe the feature you'd like in detail**
Add a command that when called shows all members inside of a role.
`?!members [role]` or `?!inrole [role]`

Suggested by Argos#4406

**Comment by Jet132** [comment]
We once considered it but after some discussion came to the conclusion that it's a rather useless command because discord already has that build in and we wouldn't be able to provide a more userfriendly or better-looking solution.
