### ISSUE TITLE
Add `botsuggestions` and `showbugs` commands

### ISSUE THREAD

**Issue by StrangeRanger** [CodeBullet-Community/BulletBot#73]
**Is your feature request related to a problem? Please describe.**
The only way to see, deleted, and all-around interact with the bot suggestions and bug reports, is by manually looking through the database.

**Describe the feature you'd like in detail**
Added commands that make it possible to see all of the bot suggestions and bug reports without having to log into the MongoDB database.
The commands should also have the option to delete any of the suggestions and bugs in the database.

**Additional information/context**
Here is a format idea:

Showing bug reports: `show bug` or `showbug`
Showing suggestions: `show botsuggest` or `showbotsuggest`

SHOULD ONLY BE USABLE MY BOTOWNERS

**Comment by Jet132** [comment]
probably won't be added, because an actual UI in the form of a web interface would be much better
